/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_tests.check" instead.
 */

#include <check.h>
#include <math.h>

#include "credits.h"
#include "postfix.h"

double str_to_double(const char *str) {
  double result;
  sscanf(str, "%lf", &result);
  return result;
}

#define PRECISION 1e-07
#define CREDIT_PRECISION 1000
#define DEPOSIT_PRECISION 10000

// Simple tests: just expressions with numbers

#define SIMPLE_COUNT 9

#define SIMPLE_EXPRESSIONS                                     \
  "5 + 3 - 1", "666 - 666 / 2", "0 * 0", "0 / 0", "0.0 / 0.0", \
      "3 - 2 - 1 - 0", "2 ^ 5", "2 ^ 3 ^ 2", "4 mod 2"

#define SIMPLE_COMPARSIONS                                                \
  5 + 3 - 1, 666 - 666 / 2.0, 0 * 0, 0.0 / 0.0, 0.0 / 0.0, 3 - 2 - 1 - 0, \
      2 * 2 * 2 * 2 * 2, 512, 4 % 2

// Simple expressions from internet

#define SIMPLE_INET_COUNT 201

#define SIMPLE_INET_EXPRESSIONS                                           \
  "191 - 5*(2*6 + 22)", "37 - 6*(9 - 5*1)", "216 - 3*(9*8 - 7)",          \
      "92 - 5*(4 - 5*4)", "300 - 2*(9*8 + 77)", "71 - 5*(7 + 3*2)",       \
      "580 - 3*(99 + 9*10)", "115 - 5*(3*10 - 8)", "138 - 4*(10 - 6*7)",  \
      "314 - 5*(1 - 6*10)", "274 - 2*(6*10 + 69)", "265 - 2*(6*10 + 63)", \
      "120 - 5*(6 - 3*9)", "104 - 5*(4 - 4*6)", "165 - 5*(18 + 2*6)",     \
      "34 - 2*(4*5 - 7)", "250 - 5*(3*7 + 29)", "96 - 3*(3 - 9*3)",       \
      "127 + 5*(9*4 - 10)", "97 - 2*(9 - 6*9)", "105 - 4*(5 - 4*8)",      \
      "76 - 3*(6*4 - 7)", "224 - 4*(2 - 7*8)", "161 - 3*(9*6 - 4)",       \
      "137 - 4*(5 - 4*8)", "60 - 5*(6 + 3*2)", "83 - 10*(3*3 - 1)",       \
      "26 - 2*(2 - 6*2)", "190 - 4*(9*6 - 8)", "12 - 3*(2*2 - 1)",        \
      "86 - 3*(10 - 4*8)", "53 - 2*(7 - 5*6)", "19 - 5*(5*2 - 7)",        \
      "65 - 2*(15 + 7*1)", "145 - 2*(35 + 7*4)", "38 - 2*(7 - 3*7)",      \
      "130 - 4*(2 - 4*8)", "70 - 4*(1 - 6*3)", "101 - 2*(22 + 8*2)",      \
      "30 - 2*(5 + 5*1)", "38 - 2*(2*10 - 4)", "145 - 5*(7 - 9*4)",       \
      "104 - 3*(4*10 - 7)", "299 + 5*(35 + 5*5)", "40 - 5*(8 - 2*7)",     \
      "175 - 4*(9*5 - 2)", "299 - 4*(3*10 + 40)", "101 - 2*(9*2 + 28)",   \
      "53 - 3*(8*2 - 6)", "89 - 2*(9*4 - 1)", "114 - 3*(3*5 + 17)",       \
      "158 + 4*(6*3 + 23)", "31 - 2*(7 - 5*4)", "178 - 2*(8*10 - 3)",     \
      "157 - 4*(9*5 - 6)", "115 - 2*(32 + 6*4)", "168 - 4*(6*3 + 21)",    \
      "235 - 5*(5*4 + 25)", "338 - 3*(9*6 + 57)", "245 - 5*(1 - 6*8)",    \
      "230 - 5*(4 - 6*8)", "14 + 9*(3*3 - 7)", "440 - 5*(47 + 8*5)",      \
      "46 - 2*(9*3 - 10)", "130 - 2*(4 - 7*9)", "351 - 3*(7*8 + 61)",     \
      "17 - 6*(9 - 4*3)", "54 - 7*(7*1 - 1)", "541 - 4*(9*7 + 67)",       \
      "132 - 3*(10 - 8*6)", "47 + 2*(13 + 3*4)", "66 + 3*(3*9 - 4)",      \
      "119 - 4*(8 - 9*4)", "79 - 6*(9 - 6*3)", "68 - 2*(4*9 - 6)",        \
      "104 - 3*(17 + 4*3)", "65 - 9*(9 - 3*5)", "56 - 2*(1 - 4*6)",       \
      "47 + 6*(9*1 - 1)", "101 - 4*(4 - 6*4)", "331 - 5*(7*10 - 5)",      \
      "103 - 2*(7*7 - 2)", "85 - 4*(8*3 - 4)", "52 - 2*(7 - 6*3)",        \
      "202 - 4*(7 - 8*7)", "20 - 10*(3*4 - 10)", "63 - 3*(9*2 - 4)",      \
      "392 - 4*(52 + 7*6)", "91 - 2*(6*6 - 5)", "236 + 3*(9*9 - 1)",      \
      "453 - 5*(48 + 5*8)", "161 - 3*(28 + 3*7)", "192 - 3*(1 - 6*10)",   \
      "112 - 5*(6*5 - 8)", "34 - 4*(2 - 2*4)", "35 - 10*(3*2 - 10)",      \
      "28 - 3*(4 - 3*4)", "134 - 3*(5*3 + 25)", "132 - 4*(3*4 + 20)",     \
      "246 - 2*(59 + 6*9)", "197 - 2*(50 + 8*6)", "224 - 2*(57 + 6*8)",   \
      "443 - 5*(9*10 - 4)", "67 - 5*(9 - 3*7)", "56 - 3*(9 - 3*8)",       \
      "442 - 4*(6*8 + 56)", "352 - 3*(8*7 + 58)", "93 - 4*(3*9 - 8)",     \
      "96 - 2*(3 - 5*8)", "60 - 2*(5 - 5*7)", "240 - 5*(27 + 9*2)",       \
      "108 - 3*(18 + 5*3)", "65 - 5*(3*7 - 9)", "254 + 4*(33 + 8*4)",     \
      "196 - 3*(9*7 - 5)", "156 - 2*(7*10 - 2)", "38 - 2*(4*3 - 6)",      \
      "127 - 5*(6 - 4*7)", "315 - 4*(41 + 7*5)", "103 + 2*(9*3 + 29)",    \
      "19 - 3*(5 - 3*4)", "422 + 5*(45 + 8*5)", "299 - 5*(7*9 - 5)",      \
      "264 - 4*(9*8 - 10)", "113 - 2*(7*8 - 3)", "52 - 2*(10 - 7*4)",     \
      "307 - 4*(7 - 9*9)", "84 - 2*(22 + 2*6)", "60 - 7*(5*2 - 3)",       \
      "90 - 5*(8*3 - 7)", "41 - 9*(2*2 - 8)", "308 - 5*(9 - 7*10)",       \
      "53 - 8*(4 - 4*2)", "29 - 2*(5*4 - 6)", "51 - 8*(2 - 7*1)",         \
      "94 - 5*(5 - 4*6)", "155 - 2*(2 - 7*10)", "134 - 2*(8*8 - 1)",      \
      "255 - 4*(33 + 6*5)", "161 - 2*(6*6 + 37)", "228 - 4*(7*9 - 9)",    \
      "140 - 2*(39 + 6*5)", "170 - 4*(2 - 7*6)", "106 - 4*(3*3 + 11)",    \
      "245 - 3*(42 + 9*4)", "277 - 3*(9*10 - 1)", "38 - 2*(2*3 + 10)",    \
      "131 + 4*(7*5 - 2)", "244 - 5*(2 - 7*7)", "288 - 4*(7*10 - 2)",     \
      "152 - 5*(1 - 9*3)", "56 - 4*(7 + 5*1)", "45 - 2*(4*1 + 9)",        \
      "608 - 4*(9*8 + 79)", "105 - 3*(4*9 - 4)", "236 - 3*(6 - 8*10)",    \
      "79 - 2*(4*9 - 3)", "344 - 2*(85 + 9*9)", "127 - 3*(6 - 9*5)",      \
      "276 - 3*(45 + 7*6)", "34 - 3*(10 - 2*8)", "46 - 9*(5 - 4*2)",      \
      "151 - 5*(2 - 3*9)", "45 - 6*(5*1 - 10)", "330 - 5*(7 - 8*9)",      \
      "31 - 2*(7*1 - 2)", "303 - 5*(7*9 - 7)", "305 - 3*(51 + 7*7)",      \
      "90 - 5*(6*1 + 8)", "119 - 3*(22 + 2*6)", "18 - 3*(5*1 - 9)",       \
      "382 - 4*(5*9 + 46)", "67 - 3*(1 - 7*3)", "47 - 7*(2*6 - 6)",       \
      "55 - 4*(9 - 7*3)", "27 - 3*(6*1 - 9)", "52 - 8*(9 - 2*7)",         \
      "28 - 5*(9 - 4*3)", "86 - 2*(3 - 5*10)", "138 - 3*(8*6 - 6)",       \
      "30 - 2*(2*6 - 2)", "70 - 3*(2*9 - 2)", "188 - 5*(5*8 - 7)",        \
      "249 - 4*(7*9 - 4)", "394 - 5*(5 - 8*10)", "61 - 2*(7*1 + 14)",     \
      "583 - 4*(7*10 + 74)", "126 - 2*(4*7 + 33)", "42 - 2*(3*7 - 3)",    \
      "40 + 2*(14 + 5*2)", "146 + 4*(23 + 5*3)", "229 - 5*(6*9 - 10)",    \
      "55 - 3*(5*1 + 8)", "96 - 4*(2*5 + 11)", "233 - 3*(4*8 + 36)",      \
      "97 - 5*(8*3 - 8)", "38 - 8*(2*2 - 5)", "192 - 4*(8 - 8*7)",        \
      "50 - 5*(9 - 9*2)", "292 - 5*(9 - 9*7)", "166 - 4*(7*7 - 9)"

#define SIMPLE_INET_COMPARSIONS                                                \
  21, 13, 21, 172, 2, 6, 13, 5, 266, 609, 16, 19, 225, 204, 15, 8, 0, 168,     \
      257, 187, 213, 25, 440, 11, 245, 0, 3, 46, 6, 3, 152, 99, 4, 21, 19, 66, \
      250, 138, 25, 10, 6, 290, 5, 599, 70, 3, 19, 9, 23, 19, 18, 322, 57, 24, \
      1, 3, 12, 10, 5, 480, 450, 32, 5, 12, 248, 0, 35, 12, 21, 246, 97, 135,  \
      231, 133, 8, 17, 119, 102, 95, 181, 6, 9, 5, 74, 398, 0, 21, 16, 29,     \
      476, 13, 14, 369, 2, 58, 75, 52, 14, 4, 20, 1, 14, 13, 127, 101, 26, 10, \
      17, 170, 120, 15, 9, 5, 514, 22, 20, 26, 237, 11, 215, 40, 847, 9, 16,   \
      7, 88, 603, 16, 11, 5, 77, 613, 85, 1, 91, 189, 291, 8, 3, 15, 12, 2,    \
      330, 26, 11, 10, 6, 263, 479, 16, 282, 8, 19, 4, 9, 458, 13, 12, 244,    \
      15, 52, 73, 276, 75, 655, 21, 23, 5, 20, 17, 30, 18, 127, 5, 103, 36,    \
      92, 43, 180, 12, 10, 22, 23, 13, 769, 19, 7, 4, 6, 88, 298, 9, 16, 12,   \
      29, 17, 46, 384, 95, 562, 6

// Middle tests: functions

#define MIDDLE_COUNT 21

#define MIDDLE_EXPRESSIONS                                                     \
  "sin(1)", "cos(0)", "tan(3.1415)", "asin(sin(1))", "acos(cos(3.1415))",      \
      "atan(1)", "atan(tan(3.1415))", "1.14 ^ 96.88", "2 ^ 20", "-3 ^ 3",      \
      "ln(4)", "log(10)", "sqrt(36)", "sin(cos(sin(cos(sqrt(3.1415)))))",      \
      "tan(atan(sqrt(20)))", "log(ln(log(10)))",                               \
      "cos(5 * sin(3.1415) - cos(2) * tan(86) - ln(6 * sqrt(24)))", "3 mod 2", \
      "15 mod 5", "1 mod 4", "2.2 mod 1.1"

#define MIDDLE_COMPARSIONS(arr_name)                                          \
  double arr_name[MIDDLE_COUNT];                                              \
  arr_name[0] = sin(1);                                                       \
  arr_name[1] = cos(0);                                                       \
  arr_name[2] = tan(3.1415);                                                  \
  arr_name[3] = asin(sin(1));                                                 \
  arr_name[4] = acos(cos(3.1415));                                            \
  arr_name[5] = atan(1);                                                      \
  arr_name[6] = atan(tan(3.1415));                                            \
  arr_name[7] = pow(1.14, 96.88);                                             \
  arr_name[8] = pow(2, 20);                                                   \
  arr_name[9] = pow(-3, 3);                                                   \
  arr_name[10] = log(4);                                                      \
  arr_name[11] = log10(10);                                                   \
  arr_name[12] = sqrt(36);                                                    \
  arr_name[13] = sin(cos(sin(cos(sqrt(3.1415)))));                            \
  arr_name[14] = tan(atan(sqrt(20)));                                         \
  arr_name[15] = log10(log(log10(10)));                                       \
  arr_name[16] = cos(5 * sin(3.1415) - cos(2) * tan(86) - log(6 * sqrt(24))); \
  arr_name[17] = fmod(3, 2);                                                  \
  arr_name[18] = fmod(15, 5);                                                 \
  arr_name[19] = fmod(1, 4);                                                  \
  arr_name[20] = fmod(2.2, 1.1);

// Incorrect expressions

#define INCORRECT_COUNT 10

#define INCORRECT_EXPRESSIONS                                               \
  "-", "+", ".0", "0.", "5.0-3.", "5.0-.3", ".3-5.0", "san(", "tun(son())", \
      "ln(sqrt())"

START_TEST(simple) {
  char *expressions[] = {SIMPLE_EXPRESSIONS};
  double comparsion[] = {SIMPLE_COMPARSIONS};
  for (size_t i = 0; i < SIMPLE_COUNT; i++) {
    char *postfix = infix_to_postfix(expressions[i]);
    char *calculated = calc_postfix(postfix, 0.0);
    if (calculated) {
      double calculated_number = str_to_double(calculated);
      if (comparsion[i] != comparsion[i])
        ck_assert_double_nan(calculated_number);
      else
        ck_assert_double_eq(calculated_number, comparsion[i]);
    } else {
      ck_assert(NULL);
      break;
    }
    free(postfix);
    free(calculated);
  }
}
END_TEST

START_TEST(simple_inet) {
  char *expressions[] = {SIMPLE_INET_EXPRESSIONS};
  double comparsion[] = {SIMPLE_INET_COMPARSIONS};
  for (size_t i = 0; i < SIMPLE_INET_COUNT; i++) {
    char *postfix = infix_to_postfix(expressions[i]);
    char *calculated = calc_postfix(postfix, 0.0);
    if (calculated) {
      double calculated_number = str_to_double(calculated);
      if (comparsion[i] != comparsion[i])
        ck_assert_double_nan(calculated_number);
      else
        ck_assert_double_eq(calculated_number, comparsion[i]);
    } else {
      ck_assert(NULL);
      break;
    }
    free(postfix);
    free(calculated);
  }
}
END_TEST

START_TEST(middle) {
  char *expressions[] = {MIDDLE_EXPRESSIONS};
  MIDDLE_COMPARSIONS(comparsion);
  for (size_t i = 0; i < MIDDLE_COUNT; i++) {
    char *postfix = infix_to_postfix(expressions[i]);
    char *calculated = calc_postfix(postfix, 0.0);
    if (calculated) {
      double calculated_number = str_to_double(calculated);
      if (comparsion[i] != comparsion[i])
        ck_assert_double_nan(calculated_number);
      else if (comparsion[i] == INFINITY || comparsion[i] == -INFINITY)
        ck_assert_double_infinite(calculated_number);
      else
        ck_assert_double_eq_tol(calculated_number, comparsion[i], PRECISION);
    } else {
      ck_assert(NULL);
      break;
    }
    free(postfix);
    free(calculated);
  }
}
END_TEST

// Incorrect expressions test

START_TEST(incorrect) {
  char *expressions[] = {INCORRECT_EXPRESSIONS};
  for (size_t i = 0; i < INCORRECT_COUNT; i++) {
    char *postfix = infix_to_postfix(expressions[i]);
    char *calculated = calc_postfix(postfix, 0.0);
    ck_assert_ptr_null(calculated);
    // In case if something went wrong...
    free(postfix);
    free(calculated);
  }
}

// Annuity credit tests

START_TEST(annuity_credit_1) {
  double sum = 1000000.0;
  double rate = 7.9;
  const char *rate_type = "Per annum";
  int term = 12;
  const char *term_type = "Months";
  double compare = 86942.0;
  double result = annuity(sum, rate, rate_type, term, term_type);
  ck_assert_double_eq_tol(result, compare, CREDIT_PRECISION);
}
END_TEST

START_TEST(annuity_credit_2) {
  double sum = 1000.0;
  double rate = 7.9;
  const char *rate_type = "Per annum";
  int term = 48;
  const char *term_type = "Months";
  double compare = 24.0;
  double result = annuity(sum, rate, rate_type, term, term_type);
  ck_assert_double_eq_tol(result, compare, CREDIT_PRECISION);
}
END_TEST

START_TEST(annuity_credit_3) {
  double sum = 490000.0;
  double rate = 17.6;
  const char *rate_type = "Per annum";
  int term = 3;
  const char *term_type = "Years";
  double compare = 17616.51;
  double result = annuity(sum, rate, rate_type, term, term_type);
  ck_assert_double_eq_tol(result, compare, CREDIT_PRECISION);
}
END_TEST

// Differentiated credit tests

START_TEST(differentiated_credit_1) {
  double sum = 1000000.0;
  double rate = 7.9;
  const char *rate_type = "Per annum";
  int term = 12;
  const char *term_type = "Months";
  double comparsions[] = {89916.67, 89368.06, 88819.44, 88270.83,
                          87722.22, 87173.61, 86625.00, 86076.39,
                          85527.78, 84979.17, 84430.56, 83881.94};
  double total_sum = sum;
  for (size_t i = 0; i < (size_t)term; i++) {
    double result =
        differentiated(total_sum, sum, rate, rate_type, term, term_type);
    ck_assert_double_eq_tol(comparsions[i], result, CREDIT_PRECISION);
    sum -= result - result * (rate / 100.0);
  }
}
END_TEST

START_TEST(differentiated_credit_2) {
  double sum = 490000.0;
  double rate = 17.6;
  const char *rate_type = "Per annum";
  int term = 1;
  const char *term_type = "Years";
  double comparsions[] = {48020.00, 47421.11, 46822.22, 46223.33,
                          45624.44, 45025.56, 44426.67, 43827.78,
                          43228.89, 42630.00, 42031.11, 41432.22};
  double total_sum = sum;
  for (size_t i = 0; i < (size_t)term * 12; i++) {
    double result =
        differentiated(total_sum, sum, rate, rate_type, term, term_type);
    ck_assert_double_eq_tol(comparsions[i], result, CREDIT_PRECISION);
    sum -= result * (1.0 - rate / 100);
  }
}
END_TEST

// Deposit tests

START_TEST(deposit_1) {
  double sum = 1000000.0;
  double rate = 17.6;
  const char *rate_type = "Per annum";
  int term = 1;
  const char *term_type = "Years";
  double compare = 1194439.51;
  double result = calc_deposit(sum, rate, rate_type, term, term_type);
  ck_assert_double_eq_tol(compare, result, DEPOSIT_PRECISION);
}
END_TEST

START_TEST(deposit_2) {
  double sum = 490000.0;
  double rate = 4.1;
  const char *rate_type = "Per annum";
  int term = 4;
  const char *term_type = "Years";
  double compare = 577163.54;
  double result = calc_deposit(sum, rate, rate_type, term, term_type);
  ck_assert_double_eq_tol(compare, result, DEPOSIT_PRECISION);
}
END_TEST

int main(void) {
  Suite *main_calc_suite = suite_create("Main calculator");
  Suite *credit_calc_suite = suite_create("Credit calculator");
  Suite *deposit_calc_suite = suite_create("Deposit calculator");

  TCase *simple_case = tcase_create("Simple expressions");
  TCase *simple_internet_case = tcase_create("Simple internet expression");
  TCase *middle_case = tcase_create("Middle expressions");
  TCase *incorrect_case = tcase_create("Incorrect expressions");

  TCase *annuity_case = tcase_create("Annuity credit");
  TCase *differentiated_case = tcase_create("Differentiated credit");

  TCase *deposit_case = tcase_create("Deposit");

  SRunner *sr = srunner_create(main_calc_suite);
  srunner_add_suite(sr, credit_calc_suite);
  srunner_add_suite(sr, deposit_calc_suite);
  int nf;

  suite_add_tcase(main_calc_suite, simple_case);
  suite_add_tcase(main_calc_suite, simple_internet_case);
  suite_add_tcase(main_calc_suite, middle_case);
  suite_add_tcase(main_calc_suite, incorrect_case);

  suite_add_tcase(credit_calc_suite, annuity_case);
  suite_add_tcase(credit_calc_suite, differentiated_case);

  suite_add_tcase(deposit_calc_suite, deposit_case);

  tcase_add_test(simple_case, simple);
  tcase_add_test(simple_internet_case, simple_inet);
  tcase_add_test(middle_case, middle);
  tcase_add_test(incorrect_case, incorrect);

  tcase_add_test(annuity_case, annuity_credit_1);
  tcase_add_test(annuity_case, annuity_credit_2);
  tcase_add_test(annuity_case, annuity_credit_3);

  tcase_add_test(differentiated_case, differentiated_credit_1);
  tcase_add_test(differentiated_case, differentiated_credit_2);

  tcase_add_test(deposit_case, deposit_1);
  tcase_add_test(deposit_case, deposit_2);

  srunner_set_fork_status(sr, CK_NOFORK);
  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
